nuget:
  account_feed: true

version: 3.6.0-rc{build}

image: Visual Studio 2017

assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
configuration: Release

before_build:
 - nuget restore
 - nuget install redis-64 -excludeversion 
 - echo This is Batman
 - cmd: redis-64\redis-server.exe --service-install 
 - cmd: redis-64\redis-server.exe --service-start 
 - cmd: set BUILD_VERSION=%appveyor_build_version%
 
after_build:
 - nuget pack NetSDK\Splitio.csproj -Version %appveyor_build_version%
 - nuget pack Splitio.Redis\Splitio.Redis.csproj -Version %appveyor_build_version%
 - nuget pack Splitio.TestSupport\Splitio.TestSupport.csproj -Version %appveyor_build_version%

artifacts:
 - path: '**\Splitio.*.nupkg'
   name: splitio-nuget

deploy:
 - provider: Environment
   name: NugetPublish
   on:
    branch: master
