nuget:
  account_feed: true

version: 3.4.2

assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
configuration: Release

before_build:
 - nuget restore
 - cmd: set BUILD_VERSION=%appveyor_build_version%
 
after_build:
 - nuget pack NetSDK\Splitio.csproj -Version %appveyor_build_version% -properties CustomAuthor="Split.IO"
 - nuget pack Splitio.Redis\Splitio.Redis.csproj -Version %appveyor_build_version% -properties CustomAuthor="Split.IO"
 - nuget pack Splitio.TestSupport\Splitio.TestSupport.csproj -Version %appveyor_build_version% -properties CustomAuthor="Split.IO"

artifacts:
 - path: '**\Splitio.*.nupkg'
   name: splitio-nuget

deploy:
 - provider: Environment
   name: NugetPublish
   on:
    branch: master
