nuget:
  account_feed: true

version: 3.6.0-rc{build}

image: Visual Studio 2017

assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
configuration: Release

# install:
#   # Install the Redis for UTs
#   - nuget install redis-64 -excludeversion
#   - redis-64\tools\redis-server.exe --service-install
#   - redis-64\tools\redis-server.exe --service-start

before_build:
 - nuget restore
 - cmd: set BUILD_VERSION=%appveyor_build_version%
 
after_build:
 - nuget pack NetSDK\Splitio.csproj -Version %appveyor_build_version%
 - nuget pack Splitio.Redis\Splitio.Redis.csproj -Version %appveyor_build_version%
 - nuget pack Splitio.TestSupport\Splitio.TestSupport.csproj -Version %appveyor_build_version%

artifacts:
 - path: '**\Splitio.*.nupkg'
   name: splitio-nuget

deploy:
 - provider: Environment
   name: NugetPublish
   on:
    branch: master
